# Generated by Django 4.1.1 on 2022-09-29 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.address')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('pos_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('identify', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id_shipping', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='paquetes.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.location')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paquetes.package')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='paquetes.user')),
                ('state', models.ManyToManyField(to='paquetes.state')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.type'),
        ),
        migrations.AddField(
            model_name='location',
            name='departamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paquetes.municipio'),
        ),
    ]
