# Generated by Django 4.1.1 on 2022-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='date',
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
