# Generated by Django 4.1.1 on 2022-09-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_date_remove_state_date_alter_shippingorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='date',
            field=models.ManyToManyField(to='paquetes.date'),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.date'),
        ),
    ]
