# Generated by Django 4.1.1 on 2022-09-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0003_state_date_alter_shippingorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='municipio',
            field=models.OneToOneField(default='a', on_delete=django.db.models.deletion.CASCADE, to='paquetes.municipio'),
        ),
        migrations.AlterField(
            model_name='location',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
    ]
