# Generated by Django 4.1.1 on 2022-09-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0005_alter_location_municipio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='departamento',
            new_name='departament',
        ),
    ]
