# Generated by Django 4.1.1 on 2022-09-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0006_rename_departamento_location_departament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departament', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        
        migrations.RemoveField(
            model_name='location',
            name='id_location',
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='pos_code',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.AlterField(
            model_name='location',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.departamento'),
        ),
    ]
