# Generated by Django 4.1.1 on 2022-09-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0007_departamento_remove_location_id_location_location_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='departament',
            new_name='departamento',
        ),
    ]
