# Generated by Django 4.1.1 on 2022-09-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0008_rename_departament_location_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departament',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
    ]
